import packageData from "../package.json";
const media = import.meta.glob("../assets/help/*.{gif,png}", { eager: true, import: "default", query: "?url" });
const updates = [
  { number: "NUEVO", title: "Di el total antes de cobrar.", tag: "2.0.2 · Descuento y prepago", guide: "prepaid-postpaid", image: "prepaid-postpaid", text: "Elige Descuento de la cuenta junto al total o abre Prepago y descuento para ver el ticket completo. El importe cambia al instante y Guardar e imprimir incluye el descuento en el ticket. En móvil, abre Prepago desde la barra inferior.", note: "Guardar prepago conserva el descuento sin imprimir ni cerrar la cuenta. Se reutiliza al cobrar una sola vez; cerrar la vista sin guardar descarta el cambio pendiente." },
  { number: "NUEVO", title: "Tú decides quién corrige un pago.", tag: "2.0.2 · Permisos", guide: "users-permissions", image: "users-permissions", text: "Solo administración puede corregir pagos por defecto. Desde Usuarios → Editar → Permiso para corregir pagos puede habilitar a una persona de Caja para su caja abierta o para cualquier caja, incluidos cortes cerrados.", note: "Puedes retirar el permiso en cualquier momento. Después de actualizar y reiniciar el servidor, vuelve a iniciar sesión en cada dispositivo." },
  { number: "NUEVO", title: "Mueve la tabla y encuentra el pago.", tag: "2.0.2 · Tablas de pagos", guide: "correct-payment", image: "correct-payment", text: "Cobros de la caja abierta y Buscador de ordenes tienen una barra visible y flechas para moverte a izquierda y derecha. Puedes usarlas con ratón, teclado o pantalla táctil.", note: "La barra conserva su posición al actualizar la vista y se oculta cuando todas las columnas caben." },
  { number: "NUEVO", title: "Conecta el teléfono y resuelve el fallo.", tag: "Ayuda 2.0.1 · WiFi y QR", guide: "lan-access", image: "lan-access", text: "En Mi perfil → Acceso web, actualiza las direcciones y comparte el enlace o QR. La guía explica qué revisar si no abre, si estás en la demo o si no aparecen los mismos datos.", note: "La demo admite acceso por red. El QR usa el puerto real y evita anunciar direcciones de red cuando el servidor sólo escucha en localhost." },
  { number: "01", title: "¿Marcaste mal el pago? Corrígelo.", tag: "Cuentas cobradas", guide: "correct-payment", image: "correct-payment", text: "En Caja o Datos → Ver cuenta, usa Corregir pago para cambiar efectivo ↔ tarjeta. Indica el motivo y revisa la propina por separado. El total no cambia y la cuenta conserva el historial.", note: "Requiere administración o permiso explícito de corrección. Administración puede corregir también después del corte, conservando el efectivo contado. No hace cargos ni devoluciones bancarias." },
  { number: "02", title: "Cada tarjeta, en su terminal.", tag: "Control de pagos", guide: "payment-terminals", image: "payment-terminals", text: "Selecciona Terminal 1, Terminal 2 o una creada por tu equipo, y marca Crédito o Débito. En Configuración → Terminales puedes nombrarlas, crear más y desactivarlas.", note: "Los cobros conservan el nombre original de la terminal. Los registros antiguos sin información se muestran como «sin registrar»." },
  { number: "03", title: "El descuento, antes de cobrar.", tag: "Prepago", guide: "prepaid-postpaid", image: "prepaid-postpaid", text: "Abre Prepago y descuento, revisa el importe y guarda o imprime. El descuento ya aparece en la cuenta del cliente; al cobrar se conserva, sin aplicarlo otra vez.", note: "El postpago mantiene el desglose como comprobante. Si cambia el pedido, se recalcula el porcentaje: entrega un prepago actualizado." },
  { number: "04", title: "Un espacio más claro para trabajar.", tag: "Diseño 2.0", guide: "create-edit-recipe", image: "create-edit-recipe", text: "Navegación por operación, administración y ayuda; mejores contrastes, buscadores más útiles y formularios de recetas con filas fáciles de agregar o quitar.", note: "Adaptado a computadora, tableta y móvil. Los cambios de receta se aplican sólo al guardar." },
  { number: "05", title: "Ayuda que empieza con una pregunta.", tag: "Asistente · Beta", guide: "create-product", image: "create-product", text: "Escribe «crear receta», «añadir plato» o «quitar producto». El asistente reconoce palabras clave, ofrece varias opciones y te lleva a la guía o al formulario según tus permisos.", note: "Funciona sin servicios de IA externos. No ejecuta cambios ni elimina datos por ti. Las 26 guías incluyen ejemplos, problemas frecuentes desplegables, comprobaciones finales y GIFs con pausas de lectura." },
];

export function renderWhatsNew() {
  return `<div class="news-layout">
    <section class="news-hero"><div><span class="news-eyebrow">NOVEDADES · V${packageData.version}</span><h2>Más claridad.<br>Más control en cada cuenta.</h2><p>Conoce los cambios, mira cómo se usan y abre su tutorial. Las imágenes son capturas reales de la demostración local, sin datos de clientes.</p></div><span class="news-version">2.0<span>LibrePOS</span></span></section>
    <div class="news-grid">${updates.map((update) => {
      const poster = media[`../assets/help/${update.image}-poster.png`];
      const gif = media[`../assets/help/${update.image}.gif`];
      return `<article class="news-card"><div class="news-card-copy"><span class="news-category">${update.number} / ${update.tag}</span><h3>${update.title}</h3><p>${update.text}</p><p class="news-note">${update.note}</p><button class="secondary-button" type="button" data-news-guide="${update.guide}">Ver tutorial paso a paso →</button></div>
        ${poster ? `<details class="news-evidence"><summary>Ver evidencia y GIF · ${update.tag}</summary><figure><img src="${poster}" alt="Captura de LibrePOS: ${update.title}" loading="lazy" width="1280" height="800" /><figcaption>Captura real. Consulta en el tutorial la versión de cada paso.</figcaption></figure>${gif ? `<details><summary>Reproducir GIF</summary><img src="${gif}" alt="Demostración animada: ${update.title}" loading="lazy" width="1280" height="800" /></details>` : ""}</details>` : ""}</article>`;
    }).join("")}</div><p class="news-footer">Antes de actualizar un equipo con datos reales, realiza una copia de seguridad. La ayuda conversacional sigue en Beta.</p>
  </div>`;
}
